### PR TITLE
Updated SushiYieldSource to use the new Yield Source Interface.

### PR DESCRIPTION
**Pull request by asselstine**
The interface has been changed because it conflicted with the ERC20
interface.  Given the likelyhood of the yield source being a token, we
had to make this breaking change.

Note that the change is not yet live on mainnet; so the tests currently
fail.

There should be unit tests, either way, that can function without
mainnet.

### CODE REVIEW

**Comment by steffenix** [comment]
I will have to update the tests and will merge this.
https://github.com/steffenix/sushi-pooltogether/blob/master/test/test.js

**Comment by steffenix** [comment]
I had a look at the project
In order to deploy `PoolWithMultipleWinnersBuilder` I have to deploy a bunch of other contracts.
It doesn't seem like hardhat let me run the deployment script of a dependency.

```
  const poolWithMultipleWinnersBuilderResult = await deploy("PoolWithMultipleWinnersBuilder", {
    args: [
      reserveRegistry,
      compoundPrizePoolProxyFactoryResult.address,
      yieldSourcePrizePoolProxyFactoryResult.address,
      stakePrizePoolProxyFactoryResult.address,
      multipleWinnersBuilderResult.address
    ],
    from: deployer
  })
```

Also, hardhat won't compile contracts that aren't inside the ./contract/ folder, which means I would have to copy the code from pooltogether code.

@asselstine do you know a way that let me reuse the deployment script and the code without copying over solidity files and the deployment script?

**Comment by steffenix** [comment]
> Note that the change is not yet live on mainnet; so the tests currently fail.
Looks like changes have been made to the interface only and not to the code.

https://github.com/pooltogether/pooltogether-pool-contracts/blob/master/contracts/yield-source/YieldSourceInterface.sol
https://github.com/pooltogether/pooltogether-pool-contracts/blob/master/contracts/prize-pool/yield-source/YieldSourcePrizePool.sol#L58

**Comment by asselstine** [comment]
@steffenix You can write unit tests that use mocks instead of real contracts!  Check out [Waffle](https://ethereum-waffle.readthedocs.io/en/latest/mock-contract.html)

There is a [Hardhat Integration of Waffle](https://hardhat.org/guides/waffle-testing.html) as well

**Comment by steffenix** [comment]
Doesn't that defeat the purpose of testing the real thing? I know that's faster to use mock but with the a small amount of tests that's ok to fork mainnet

**Comment by asselstine** [comment]
Nothing beats a unit test- they run extremely quickly and allow you to explore edge cases.

That being said, fork tests are always needed too!  They can be very slow and heavy weight, however

**Pull request merged**
