### PR TITLE
update tests to use the new interface

### PR DESCRIPTION
**Pull request by steffenix**
This branch has working tests, it's using: https://github.com/pooltogether/pooltogether-pool-contracts/pull/281/files

@asselstine

### CODE REVIEW

**Comment by asselstine** [comment]
Wow!  You deployed them all.  You have no fear of hard work, do you? :)

I highly recommend treating each contact as an isolated unit: what you really want to test are the edge cases and behaviour of the functions you've written.

The [TokenFaucet test](https://github.com/pooltogether/pooltogether-pool-contracts/blob/d6d79029e7b272ed71c2911d5d60bdb354cd0271/test/TokenFaucet.test.js) is one example of this.  The TokenFaucet plugs into a Prize Strategy, but it can be tested entirely in isolation.

This approach also makes it much easier to find bugs!

**Comment by steffenix** [comment]
Ok understood I will add a unittest that just test the contract as an isolated unit.

**Comment by steffenix** [comment]
@asselstine I have added a series of test that test the contract without using the pooltogether pools.

https://github.com/steffenix/sushi-pooltogether/blob/981e57def146b7e3b314e55d72d8b459ff238c17/test/unit_test.js

**Comment by steffenix** [comment]
Can you validate the grant ?

**Pull request merged**
